### ISSUE TITLE
Why did you add skip bools to each test?

### ISSUE THREAD

**Issue by enyo** [exitlive/currency-cloud-dart#11]
...when there is `@Skip("Don't run integration tests by default")` annotation at the beginning?

**Comment by queltos** [comment]
I used them to skip single tests more easily. Found it to be a bit annoying to add the `skip` named parameter at the end of each test. Felt way more convenient to just set the `skip` variable before the test to something not `null` for skipping. e.g. if I want to skip the first three tests I'd set `skip` to some string before the first test and to `null` before the fourth test instead of having to add the `skip: 'something'` to every one of the first three tests.
